"""Initial migration

Revision ID: 44afed16c078
Revises: 
Create Date: 2024-08-31 15:20:30.553899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44afed16c078'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('date')

    # ### end Alembic commands ###
